#!/usr/bin/env bash
# Disposable stack, fresh work volume and generated media. Does not use run.sh/.env.
# Usage: bash ci/integration.sh /absolute/path/to/main_os/ota_v257
# Build snowsky-disc-qemu-ci first. Requires Compose >=2.36 and a privileged Docker engine.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
export OTA_DIR="$(cd "${1:?path to OTA chunks}" && pwd)"
export FW_VERSION="${FW_VERSION:-2.57}"
CI_SCENARIO="${CI_SCENARIO:-full}"
CI_IDLE_PHASE="${CI_IDLE_PHASE:-all}"
case "$CI_IDLE_PHASE" in all|quiet|power|usb) ;; *) echo 'Unknown CI_IDLE_PHASE' >&2; exit 2;; esac
case "$CI_SCENARIO" in full|queue|queue-reads|settings|themes|preferences|playlists|library|library-delete|scan-cancel|library-reset|track-end|formats|discovery|idle|idle-usb) ;; *) echo 'Unknown CI_SCENARIO' >&2; exit 2;; esac
if [[ ( "$CI_SCENARIO" = library || "$CI_SCENARIO" = library-delete ) && "$FW_VERSION" != 2.57 ]]; then
  echo 'Genre/folder acceptance requires active firmware V2.57' >&2
  exit 2
fi
if [[ "$CI_SCENARIO" = themes && "$FW_VERSION" != 2.57 ]]; then
  echo 'Custom-style acceptance requires active firmware V2.57' >&2
  exit 2
fi
if [[ "$CI_SCENARIO" = preferences || "$CI_SCENARIO" = playlists || "$CI_SCENARIO" = scan-cancel || "$CI_SCENARIO" = library-reset || "$CI_SCENARIO" = track-end || "$CI_SCENARIO" = formats || "$CI_SCENARIO" = discovery || "$CI_SCENARIO" = idle || "$CI_SCENARIO" = idle-usb ]] && [ "$FW_VERSION" != 2.57 ]; then
  echo 'Preference/playlist/scan-cancel/library-reset/track-end/formats/discovery/idle acceptance requires active firmware V2.57' >&2
  exit 2
fi
CI_TMP="$(mktemp -d "${TMPDIR:-/tmp}/snowsky-disc-ci.XXXXXXXX")"
CI_ID="snowsky-disc-ci-$(basename "$CI_TMP" | tr '[:upper:].' '[:lower:]-')"
export EMU_IMAGE="${EMU_IMAGE:-snowsky-disc-qemu-ci}"
export EMU_CONTAINER_NAME="$CI_ID-emu"
export WORK_VOLUME="$CI_ID-work"
export SD_DIR="$CI_TMP/sdcard"
mkdir "$SD_DIR"
compose() { docker compose --env-file /dev/null --profile wsbridge -p "$CI_ID" -f compose.yaml -f ci/compose.yml "$@"; }
cleanup() {
  # Opt-in local diagnostics before the disposable volume is removed. Never
  # enabled/uploaded by hosted Actions; guest logs may contain private data.
  if [ -n "${CI_LOGS:-}" ]; then
    mkdir -p "$CI_LOGS"
    compose cp emu:/work/mq_player.log "$CI_LOGS/mq_player.log" || true
    compose cp emu:/work/mq_ui.log "$CI_LOGS/mq_ui.log" || true
    if [[ "$CI_SCENARIO" = idle || "$CI_SCENARIO" = idle-usb ]]; then
      compose cp emu:/work/idle-evidence "$CI_LOGS/idle-evidence" || true
    fi
  fi
  if [ -n "${CI_SHOTS:-}" ]; then
    mkdir -p "$CI_SHOTS"
    compose cp emu:/work/shots/. "$CI_SHOTS" || true
    if [[ "$CI_SCENARIO" = idle || "$CI_SCENARIO" = idle-usb ]]; then
      compose cp emu:/work/idle-shots/. "$CI_SHOTS" || true
    fi
  fi
  # Only this randomly named stack/volume; never snowsky-disc-work or the interactive stack.
  compose exec -T emu bash /repo/ci/cleanup.sh || true
  compose down --volumes --timeout 5
  # Media is generated by us; OTA input and the user's sdcard are never removed.
  docker run --rm --network none -v "$CI_TMP:/ci-temp" -v "$PWD:/repo:ro" "$EMU_IMAGE" \
    python3 -c 'from pathlib import Path; from tests.fixtures.fixture import NAMES; d=Path("/ci-temp/sdcard/Кириллица Ё й"); [(d/n).unlink(missing_ok=True) for n in NAMES]; d.rmdir() if d.exists() else None'
  rmdir "$SD_DIR" "$CI_TMP"
}
trap cleanup EXIT
compose config --quiet
docker run --rm --network none -v "$PWD:/repo:ro" -v "$SD_DIR:/fixtures" \
  "$EMU_IMAGE" python3 -B -m tests.fixtures.fixture /fixtures
compose up -d --no-build --wait --wait-timeout 60
compose exec -T emu bash /repo/emulator/scripts/00_extract_rootfs.sh /ota
compose exec -T emu bash /repo/emulator/scripts/10_setup_env.sh
if [ "$CI_SCENARIO" = idle ]; then
  compose exec -T emu python3 -B -m tests.integration.idle_check --phase "$CI_IDLE_PHASE"
  exit 0
fi
if [ "$CI_SCENARIO" = idle-usb ]; then
  compose exec -T emu python3 -B -m tests.integration.idle_check --phase usb
  exit 0
fi
if [ "$FW_VERSION" = 2.57 ]; then
  compose exec -T emu python3 -B -m tests.integration.awake_check --configure
fi
compose exec -T emu bash /repo/emulator/scripts/20_boot.sh
if [ "$FW_VERSION" = 2.57 ]; then
  compose exec -T emu python3 -B -m tests.integration.awake_check
fi
if [[ "$FW_VERSION" = 2.57 && ( "$CI_SCENARIO" = full || "$CI_SCENARIO" = discovery ) ]]; then
  compose exec -T emu python3 -B -m tests.integration.discovery_check
  if [ "$CI_SCENARIO" = discovery ]; then exit 0; fi
fi
if [ "$CI_SCENARIO" = scan-cancel ]; then
  compose exec -T emu python3 -B -m tests.integration.scan_cancel_check
  exit 0
fi
if [ "$CI_SCENARIO" = library-reset ]; then
  compose exec -T emu python3 -B -m tests.integration.library_reset_check
  exit 0
fi
if [ "$CI_SCENARIO" = track-end ]; then
  compose exec -T emu python3 -B -m tests.integration.track_end_check
  exit 0
fi
if [ "$CI_SCENARIO" = formats ]; then
  compose exec -T emu python3 -B -m tests.integration.formats_check
  exit 0
fi
if [ "$CI_SCENARIO" = library-delete ]; then
  compose exec -T emu python3 -B -m tests.integration.library_delete_check
  exit 0
fi
if [ "$CI_SCENARIO" = library ]; then
  compose exec -T emu python3 -B -m tests.integration.library_check
  exit 0
fi
if [ "$CI_SCENARIO" = themes ]; then
  compose exec -T emu python3 -B -m tests.integration.modes_themes_check --themes-only
  exit 0
fi
if [ "$CI_SCENARIO" = queue-reads ]; then
  compose exec -T emu python3 -B -m tests.integration.queue_reads_check --prepare
else
  compose exec -T emu python3 -B -m tests.integration.guest_check
fi
# Exercise peripherals after the stock scan but BEFORE selecting a track.
# Paused playback can retain the selected file. Rebooting after those probes
# still left the card busy in hosted V2.40 CI; it is not an idle-card fixture.
# Restart here to dismiss the scanner UI without carrying playback state.
compose exec -T emu bash /repo/emulator/scripts/20_boot.sh
if [ "$CI_SCENARIO" = queue ]; then
  compose exec -T emu python3 -B -m tests.integration.queue_check --fresh
  exit 0
fi
if [ "$CI_SCENARIO" = queue-reads ]; then
  compose exec -T emu python3 -B -m tests.integration.queue_reads_check --fresh
  exit 0
fi
if [ "$CI_SCENARIO" = settings ]; then
  compose exec -T emu python3 -B -m tests.integration.settings_check
  exit 0
fi
if [ "$CI_SCENARIO" = preferences ]; then
  compose exec -T emu python3 -B -m tests.integration.preferences_check
  exit 0
fi
if [ "$CI_SCENARIO" = playlists ]; then
  compose exec -T emu python3 -B -m tests.integration.playlists_check
  exit 0
fi
compose exec -T emu python3 -B -m tests.integration.viewer_peripherals
compose exec -T wsbridge python3 -B -m controller.diagnostics.verify_websocket --tcp-host emu --control
compose exec -T emu python3 -B -m tests.integration.guest_check --audio
compose exec -T emu python3 -B -m tests.integration.controls
compose exec -T emu python3 -B -m tests.integration.remote_control
compose exec -T emu python3 -B -m tests.integration.queue_check
compose exec -T emu python3 -B -m tests.integration.queue_reads_check
compose exec -T emu python3 -B -m tests.integration.http_check
if [ "$FW_VERSION" = 2.57 ]; then
  compose exec -T emu python3 -B -m tests.integration.playlists_check
fi
compose exec -T emu python3 -B -m tests.integration.settings_check
compose exec -T emu python3 -B -m tests.integration.modes_themes_check
compose exec -T emu bash /repo/tests/integration/confinement.sh
if [ "$FW_VERSION" = 2.57 ]; then
  compose exec -T emu python3 -B -m tests.integration.library_check
  compose exec -T emu python3 -B -m tests.integration.formats_check
  compose exec -T emu python3 -B -m tests.integration.track_end_check
  compose exec -T emu python3 -B -m tests.integration.scan_cancel_check
  compose exec -T emu python3 -B -m tests.integration.library_reset_check
  compose exec -T emu python3 -B -m tests.integration.storage_check --disposable
  compose exec -T emu python3 -B -m tests.integration.preferences_check
fi
