#!/usr/bin/env bash
# Disposable stack, fresh work volume and generated media. Does not use run.sh/.env.
# Usage: bash ci/integration.sh /absolute/path/to/main_os/ota_v257
# Build diskos-qemu-ci first. Requires Compose >=2.36 and a privileged Docker engine.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
export OTA_DIR="$(cd "${1:?path to OTA chunks}" && pwd)"
export FW_VERSION="${FW_VERSION:-2.57}"
CI_SCENARIO="${CI_SCENARIO:-full}"
case "$CI_SCENARIO" in full|queue|queue-reads|settings|preferences|playlists|scan-cancel|library-reset) ;; *) echo 'Unknown CI_SCENARIO' >&2; exit 2;; esac
if [[ "$CI_SCENARIO" = preferences || "$CI_SCENARIO" = playlists || "$CI_SCENARIO" = scan-cancel || "$CI_SCENARIO" = library-reset ]] && [ "$FW_VERSION" != 2.57 ]; then
  echo 'Preference/playlist/scan-cancel/library-reset acceptance requires active firmware V2.57' >&2
  exit 2
fi
CI_TMP="$(mktemp -d "${TMPDIR:-/tmp}/diskos-ci.XXXXXXXX")"
CI_ID="diskos-ci-$(basename "$CI_TMP" | tr '[:upper:].' '[:lower:]-')"
export EMU_IMAGE="${EMU_IMAGE:-diskos-qemu-ci}"
export EMU_CONTAINER_NAME="$CI_ID-emu"
export WORK_VOLUME="$CI_ID-work"
export SD_DIR="$CI_TMP/sdcard"
mkdir "$SD_DIR"
compose() { docker compose --env-file /dev/null --profile wsbridge -p "$CI_ID" -f compose.yaml -f ci/compose.yml "$@"; }
cleanup() {
  # Opt-in local diagnostics before the disposable volume is removed. Never
  # enabled/uploaded by hosted Actions; guest logs may contain private data.
  if [ -n "${CI_LOGS:-}" ]; then
    mkdir -p "$CI_LOGS"
    compose cp emu:/work/mq_player.log "$CI_LOGS/mq_player.log" || true
    compose cp emu:/work/mq_ui.log "$CI_LOGS/mq_ui.log" || true
  fi
  if [ -n "${CI_SHOTS:-}" ]; then
    mkdir -p "$CI_SHOTS"
    compose cp emu:/work/shots/. "$CI_SHOTS" || true
  fi
  # Only this randomly named stack/volume; never diskos-work or the interactive stack.
  compose exec -T emu bash /repo/ci/cleanup.sh || true
  compose down --volumes --timeout 5
  # Media is generated by us; OTA input and the user's sdcard are never removed.
  docker run --rm --network none -v "$CI_TMP:/ci-temp" -v "$PWD:/repo:ro" "$EMU_IMAGE" \
    python3 -c 'from pathlib import Path; import sys; sys.path.insert(0,"/repo/ci"); from fixture import NAMES; d=Path("/ci-temp/sdcard/Кириллица Ё й"); [(d/n).unlink(missing_ok=True) for n in NAMES]; d.rmdir() if d.exists() else None'
  rmdir "$SD_DIR" "$CI_TMP"
}
trap cleanup EXIT
compose config --quiet
docker run --rm --network none -v "$PWD:/repo:ro" -v "$SD_DIR:/fixtures" \
  "$EMU_IMAGE" python3 -B /repo/ci/fixture.py /fixtures
compose up -d --no-build --wait --wait-timeout 60
compose exec -T emu bash /repo/scripts/00_extract_rootfs.sh /ota
compose exec -T emu bash /repo/scripts/10_setup_env.sh
if [ "$FW_VERSION" = 2.57 ]; then
  compose exec -T emu python3 -B /repo/ci/awake_check.py --configure
fi
compose exec -T emu bash /repo/scripts/20_boot.sh
if [ "$FW_VERSION" = 2.57 ]; then
  compose exec -T emu python3 -B /repo/ci/awake_check.py
fi
if [ "$CI_SCENARIO" = scan-cancel ]; then
  compose exec -T emu python3 -B /repo/ci/scan_cancel_check.py
  exit 0
fi
if [ "$CI_SCENARIO" = library-reset ]; then
  compose exec -T emu python3 -B /repo/ci/library_reset_check.py
  exit 0
fi
if [ "$CI_SCENARIO" = queue-reads ]; then
  compose exec -T emu python3 -B /repo/ci/queue_reads_check.py --prepare
else
  compose exec -T emu python3 -B /repo/ci/guest_check.py
fi
# Exercise peripherals after the stock scan but BEFORE selecting a track.
# Paused playback can retain the selected file. Rebooting after those probes
# still left the card busy in hosted V2.40 CI; it is not an idle-card fixture.
# Restart here to dismiss the scanner UI without carrying playback state.
compose exec -T emu bash /repo/scripts/20_boot.sh
if [ "$CI_SCENARIO" = queue ]; then
  compose exec -T emu python3 -B /repo/ci/queue_check.py --fresh
  exit 0
fi
if [ "$CI_SCENARIO" = queue-reads ]; then
  compose exec -T emu python3 -B /repo/ci/queue_reads_check.py --fresh
  exit 0
fi
if [ "$CI_SCENARIO" = settings ]; then
  compose exec -T emu python3 -B /repo/ci/settings_check.py
  exit 0
fi
if [ "$CI_SCENARIO" = preferences ]; then
  compose exec -T emu python3 -B /repo/ci/preferences_check.py
  exit 0
fi
if [ "$CI_SCENARIO" = playlists ]; then
  compose exec -T emu python3 -B /repo/ci/playlists_check.py
  exit 0
fi
compose exec -T emu python3 -B /repo/ci/viewer_peripherals.py
compose exec -T wsbridge python3 -B /repo/tools/verify_websocket.py --tcp-host emu --control
compose exec -T emu python3 -B /repo/ci/guest_check.py --audio
compose exec -T emu python3 -B /repo/ci/controls.py
compose exec -T emu python3 -B /repo/ci/remote_control.py
compose exec -T emu python3 -B /repo/ci/queue_check.py
compose exec -T emu python3 -B /repo/ci/queue_reads_check.py
compose exec -T emu python3 -B /repo/ci/http_check.py
if [ "$FW_VERSION" = 2.57 ]; then
  compose exec -T emu python3 -B /repo/ci/playlists_check.py
fi
compose exec -T emu python3 -B /repo/ci/settings_check.py
compose exec -T emu python3 -B /repo/ci/modes_themes_check.py
compose exec -T emu bash /repo/ci/confinement.sh
if [ "$FW_VERSION" = 2.57 ]; then
  compose exec -T emu python3 -B /repo/ci/scan_cancel_check.py
  compose exec -T emu python3 -B /repo/ci/library_reset_check.py
  compose exec -T emu python3 -B /repo/ci/storage_check.py --disposable
  compose exec -T emu python3 -B /repo/ci/preferences_check.py
fi
