#!/usr/bin/env bash
# Disposable stack, fresh work volume and generated media. Does not use emulator/run.sh or emulator/.env.
# Usage: bash ci/integration.sh /absolute/path/to/main_os/ota_v257
# Build snowsky-disc-qemu-ci first. Requires Compose >=2.36 and a privileged Docker engine.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
export OTA_DIR="$(cd "${1:?path to OTA chunks}" && pwd)"
export FW_VERSION="${FW_VERSION:-$(cat firmware/active-version)}"
CI_SCENARIO="${CI_SCENARIO:-full}"
CI_IDLE_PHASE="${CI_IDLE_PHASE:-all}"
case "$CI_IDLE_PHASE" in all|quiet|power|usb) ;; *) echo 'Unknown CI_IDLE_PHASE' >&2; exit 2;; esac
case "$CI_SCENARIO" in full|queue|queue-reads|settings|peq|sacd|themes|preferences|playlists|library|library-delete|scan-cancel|library-reset|track-end|formats|discovery|idle|idle-usb) ;; *) echo 'Unknown CI_SCENARIO' >&2; exit 2;; esac
if [ "$CI_SCENARIO" = sacd ]; then
  test -f "${CI_SACD_ISO:?sacd requires an explicitly approved local ISO file}"
fi
export EMU_IMAGE="${EMU_IMAGE:-snowsky-disc-qemu-ci}"
profile() { docker run --rm --network none -v "$PWD:/repo:ro" "$EMU_IMAGE" python3 -B -m firmware.profile "$@" --version "$FW_VERSION"; }
profile require-scenario "$CI_SCENARIO"
CI_CAPABILITIES="$(profile get capabilities)"
CI_ACCEPTANCE="$(profile get acceptance)"
CI_FULL_SCENARIOS="$(profile get full_scenarios)"
has_feature() { [[ "$CI_CAPABILITIES" == *\"$1\"* ]]; }
has_scenario() { [[ "$CI_ACCEPTANCE" == *\"$1\"* ]]; }
full_scenario() { [[ "$CI_FULL_SCENARIOS" == *\"$1\"* ]]; }
CI_TMP="$(mktemp -d "${TMPDIR:-/tmp}/snowsky-disc-ci.XXXXXXXX")"
CI_ID="snowsky-disc-ci-$(basename "$CI_TMP" | tr '[:upper:].' '[:lower:]-')"
export EMU_IMAGE="${EMU_IMAGE:-snowsky-disc-qemu-ci}"
export EMU_CONTAINER_NAME="$CI_ID-emu"
export WORK_VOLUME="$CI_ID-work"
export SD_DIR="$CI_TMP/sdcard"
mkdir "$SD_DIR"
compose() { docker compose --project-directory "$PWD" --env-file /dev/null --profile wsbridge -p "$CI_ID" -f emulator/compose.yaml -f ci/compose.yml "$@"; }
cleanup() {
  # Opt-in local diagnostics before the disposable volume is removed. Never
  # enabled/uploaded by hosted Actions; guest logs may contain private data.
  if [ -n "${CI_LOGS:-}" ]; then
    mkdir -p "$CI_LOGS"
    compose cp emulator:/work/mq_player.log "$CI_LOGS/mq_player.log" || true
    compose cp emulator:/work/mq_ui.log "$CI_LOGS/mq_ui.log" || true
    if [[ "$CI_SCENARIO" = idle || "$CI_SCENARIO" = idle-usb ]]; then
      compose cp emulator:/work/idle-evidence "$CI_LOGS/idle-evidence" || true
    fi
  fi
  if [ -n "${CI_SHOTS:-}" ]; then
    mkdir -p "$CI_SHOTS"
    compose cp emulator:/work/shots/. "$CI_SHOTS" || true
    if [[ "$CI_SCENARIO" = idle || "$CI_SCENARIO" = idle-usb ]]; then
      compose cp emulator:/work/idle-shots/. "$CI_SHOTS" || true
    fi
  fi
  # Only this randomly named stack/volume; never snowsky-disc-work or the interactive stack.
  compose exec -T emulator bash /repo/ci/cleanup.sh || true
  compose down --volumes --timeout 5
  # Media is generated by us; OTA input and the user's sdcard are never removed.
  docker run --rm --network none -v "$CI_TMP:/ci-temp" -v "$PWD:/repo:ro" "$EMU_IMAGE" \
    python3 -c 'from pathlib import Path; from tests.fixtures.fixture import NAMES; d=Path("/ci-temp/sdcard/Кириллица Ё й"); [(d/n).unlink(missing_ok=True) for n in NAMES]; d.rmdir() if d.exists() else None'
  if [ "$CI_SCENARIO" = sacd ]; then
    rm -f "$SD_DIR/SACD CI/source.iso"
    rmdir "$SD_DIR/SACD CI"
  fi
  rmdir "$SD_DIR" "$CI_TMP"
}
trap cleanup EXIT
compose config --quiet
docker run --rm --network none -v "$PWD:/repo:ro" -v "$SD_DIR:/fixtures" \
  "$EMU_IMAGE" python3 -B -m tests.fixtures.fixture /fixtures
if [ "$CI_SCENARIO" = sacd ]; then
  mkdir "$SD_DIR/SACD CI"
  cp "$CI_SACD_ISO" "$SD_DIR/SACD CI/source.iso"
fi
compose up -d --no-build --wait --wait-timeout 60
compose exec -T emulator bash /repo/emulator/scripts/00_extract_rootfs.sh /ota
compose exec -T emulator bash /repo/emulator/scripts/10_setup_env.sh
if [ "$CI_SCENARIO" = idle ]; then
  compose exec -T emulator python3 -B -m tests.integration.idle_check --phase "$CI_IDLE_PHASE"
  exit 0
fi
if [ "$CI_SCENARIO" = idle-usb ]; then
  compose exec -T emulator python3 -B -m tests.integration.idle_check --phase usb
  exit 0
fi
if has_feature display_fixture; then
  compose exec -T emulator python3 -B -m tests.integration.awake_check --configure
fi
compose exec -T emulator bash /repo/emulator/scripts/20_boot.sh
if has_feature display_fixture; then
  compose exec -T emulator python3 -B -m tests.integration.awake_check
fi
if has_feature discovery && [[ "$CI_SCENARIO" = full || "$CI_SCENARIO" = discovery ]]; then
  compose exec -T emulator python3 -B -m tests.integration.discovery_check
  if [ "$CI_SCENARIO" = discovery ]; then exit 0; fi
fi
if [ "$CI_SCENARIO" = scan-cancel ]; then
  compose exec -T emulator python3 -B -m tests.integration.scan_cancel_check
  exit 0
fi
if [ "$CI_SCENARIO" = library-reset ]; then
  compose exec -T emulator python3 -B -m tests.integration.library_reset_check
  exit 0
fi
if [ "$CI_SCENARIO" = track-end ]; then
  compose exec -T emulator python3 -B -m tests.integration.track_end_check
  exit 0
fi
if [ "$CI_SCENARIO" = formats ]; then
  compose exec -T emulator python3 -B -m tests.integration.formats_check
  exit 0
fi
if [ "$CI_SCENARIO" = sacd ]; then
  compose exec -T emulator python3 -B -m tests.integration.sacd_check
  exit 0
fi
if [ "$CI_SCENARIO" = peq ]; then
  compose exec -T emulator python3 -B -m tests.integration.peq_check
  exit 0
fi
if [ "$CI_SCENARIO" = library-delete ]; then
  compose exec -T emulator python3 -B -m tests.integration.library_delete_check
  exit 0
fi
if [ "$CI_SCENARIO" = library ]; then
  compose exec -T emulator python3 -B -m tests.integration.library_check
  exit 0
fi
if [ "$CI_SCENARIO" = themes ]; then
  compose exec -T emulator python3 -B -m tests.integration.modes_themes_check --themes-only
  exit 0
fi
if [ "$CI_SCENARIO" = queue-reads ]; then
  compose exec -T emulator python3 -B -m tests.integration.queue_reads_check --prepare
else
  compose exec -T emulator python3 -B -m tests.integration.guest_check
fi
# Exercise peripherals after the stock scan but BEFORE selecting a track.
# Paused playback can retain the selected file. Rebooting after those probes
# still left the card busy in hosted V2.40 CI; it is not an idle-card fixture.
# Restart here to dismiss the scanner UI without carrying playback state.
compose exec -T emulator bash /repo/emulator/scripts/20_boot.sh
if [ "$CI_SCENARIO" = queue ]; then
  compose exec -T emulator python3 -B -m tests.integration.queue_check --fresh
  compose exec -T emulator python3 -B -m tests.integration.web_session_check
  exit 0
fi
if [ "$CI_SCENARIO" = queue-reads ]; then
  compose exec -T emulator python3 -B -m tests.integration.queue_reads_check --fresh
  exit 0
fi
if [ "$CI_SCENARIO" = settings ]; then
  compose exec -T emulator python3 -B -m tests.integration.settings_check
  exit 0
fi
if [ "$CI_SCENARIO" = preferences ]; then
  compose exec -T emulator python3 -B -m tests.integration.preferences_check
  exit 0
fi
if [ "$CI_SCENARIO" = playlists ]; then
  compose exec -T emulator python3 -B -m tests.integration.playlists_check
  exit 0
fi
compose exec -T emulator python3 -B -m tests.integration.viewer_peripherals
compose exec -T wsbridge python3 -B -m controller.diagnostics.verify_websocket --tcp-host emulator --control
compose exec -T emulator python3 -B -m tests.integration.guest_check --audio
compose exec -T emulator python3 -B -m tests.integration.controls
compose exec -T emulator python3 -B -m tests.integration.remote_control
compose exec -T emulator python3 -B -m tests.integration.queue_check
compose exec -T emulator python3 -B -m tests.integration.queue_reads_check
compose exec -T emulator python3 -B -m tests.integration.web_session_check
compose exec -T emulator python3 -B -m tests.integration.http_check
if has_scenario playlists; then
  compose exec -T emulator python3 -B -m tests.integration.playlists_check
fi
compose exec -T emulator python3 -B -m tests.integration.settings_check
compose exec -T emulator python3 -B -m tests.integration.modes_themes_check
compose exec -T emulator bash /repo/tests/integration/confinement.sh
if full_scenario library; then
  compose exec -T emulator python3 -B -m tests.integration.library_check
fi
if full_scenario formats; then
  compose exec -T emulator python3 -B -m tests.integration.formats_check
fi
if full_scenario track-end; then
  compose exec -T emulator python3 -B -m tests.integration.track_end_check
fi
if full_scenario scan-cancel; then
  compose exec -T emulator python3 -B -m tests.integration.scan_cancel_check
fi
if full_scenario library-reset; then
  compose exec -T emulator python3 -B -m tests.integration.library_reset_check
fi
if full_scenario storage; then
  compose exec -T emulator python3 -B -m tests.integration.storage_check --disposable
fi
if full_scenario preferences; then
  compose exec -T emulator python3 -B -m tests.integration.preferences_check
fi

compose exec -T emulator python3 -B -m tests.integration.viewer_check
