"""Structural interfaces for guarded operations; raw transports are separate."""
from typing import Any, Literal, Protocol

from controller.compatibility import IdentityClient
from controller.wire import WireState

ControlAction = Literal['pause', 'resume', 'next', 'previous']
CurrentAction = Literal['now_playing', 'like', 'dislike', 'volume']
MutationPhase = Literal['selection', 'mode', 'favorite', 'volume']


class PlaybackReader(IdentityClient, Protocol):
    timeout: float

    def now_playing(self) -> WireState: ...
    def take_events(self) -> list[tuple[str, bytes]]: ...


class ControlClient(PlaybackReader, Protocol):
    mutation_attempted: bool

    def begin_phase(self, name: MutationPhase) -> None: ...
    def wait_for_mutation(self) -> None: ...
    def scan_guard(self) -> None: ...
    def set_volume(self, value: int) -> None: ...
    def set_favorite(self, value: bool) -> None: ...
    def play_pause(self) -> None: ...
    def next_track(self) -> None: ...
    def previous_track(self) -> None: ...
    def play_mode(self) -> int: ...
    def set_play_mode(self, mode: int) -> None: ...


class SelectionClient(ControlClient, Protocol):
    """Advanced borrowed operation surface for fresh catalog selection."""
    def play_queue_index(self, index: int, *, http: Any = None) -> None: ...
    def play_artist(self, artist: str, index: int | None = None, *,
                    album: str | None = None, http: Any) -> None: ...
    def play_album(self, album: str, index: int | None = None, *, http: Any) -> None: ...
